### ISSUE TITLE
PCA crash if the data is only one element

### ISSUE THREAD

**Issue by lpatiny** [mljs/pca#1]
Check the view

http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F322d373f937cb95a6706334d60a2c544%2Fview.json

And use as data

1,1

**Comment by lpatiny** [comment]
Also crash if the data are
1,0
2,0
(infinite loop)

**Comment by targos** [comment]
It's on me. That happens in the SVD (matrix package)

**Comment by targos** [comment]
First issue is from the matrix package, but the second one is here. I will create a testcase based on matlab code

**Comment by targos** [comment]
I believe this is fixed now
