### ISSUE TITLE
Noob question: How do I project my data into the PCA space?

### ISSUE THREAD

**Issue by light24bulbs** [mljs/pca#11]
For instance check out how this simple ruby library works.

https://github.com/gbuesing/pca

It outputs the dataset in the desired number of dimensions, ready to graph. Is this easy with your library and I am just missing something obvious?  

Thanks!

**Comment by targos** [comment]
To project a dataset into the PCA space, you should use the `predict` method. You can call it with the original data that was passed to the PCA constructor.

See https://github.com/mljs/pca#usage for a code example (replace `newPoints` with `dataset`)

**Comment by light24bulbs** [comment]
Oh! Thank you! I thought that was just for new data.  It makes sense now.
Thank you!

**Comment by transitive-bullshit** [comment]
I also found this confusing 😂 Since the example uses `newPoints`, I thought it meant the projection was already computed for the original data somewhere, but I was having a hard time figuring out where.
