### ISSUE TITLE
Mono dimensional arrays: TypeError: First argument must be a positive number or an array

### ISSUE THREAD

**Issue by loretoparisi** [mljs/pca#15]
I have an array of features with size N with M samples dataset. This is a vector N-dimensional of hashes representing a fingerprint of an audio file. I would like to run PCA on it using this library. So assumed my dataset size is M x N, how to run against this library?

**Comment by andcastillo** [comment]
var db3 = [[1,2,3], [2,0,2], [3,4,5], [0, 6, 2]];
var pca = new PCA(db3, { scale: true });
//reduce to 2 columns
var db2 = pca.predict(db3, {nComponents: 2}))

Does this help??

**Comment by loretoparisi** [comment]
@andcastillo I get an array of `null`

```javascript
var components = new PCA(hashes, { scale: true });
consoleLogger.info("PCA:%@",components);
var reduced = components.predict(components, {nComponents: 2});
consoleLogger.info("predict:%@",reduced);
```

where `hashes` is like https://gist.github.com/loretoparisi/01d19c958ba89c1200eb029b178c6c06

**Comment by jobo322** [comment]
Hello @loretoparisi, is there one variable for M samples? if yes, 
 this is a weird dimension, what do you expect from PCA of this dataset?

**Comment by loretoparisi** [comment]
@jobo322 hello, so I have added more samples so to obtain a M X N matrix where each array is of size N. I have padded my input data with zeros in order to have the same size, but I'm now getting a `RangeError: Inconsistent array dimensions`

```bash
 [Thu Jan 10 2019 14:51:57 GMT+0100 (CET)] PCA: calculating eigenvectors of 3 hashes of size 10176
 [Thu Jan 10 2019 14:51:57 GMT+0100 (CET)] hashes num:3 min:6004 max:10176
0 10176
1 10176
2 10176
 [Thu Jan 10 2019 14:51:57 GMT+0100 (CET)] error RangeError: Inconsistent array dimensions
```

**Comment by loretoparisi** [comment]
@jobo322 Hello! So I have zero-padded my samples to max size in order to have M X N matrix of M samples of size N:

```bash
 [Thu Jan 10 2019 14:59:38 GMT+0100 (CET)] PCA: calculating eigenvectors of 3 hashes
 [Thu Jan 10 2019 14:59:38 GMT+0100 (CET)] hashes num:3 min:6004 max:10176
0 10176
1 10176
2 10176
```

I'm still getting

```
 [Thu Jan 10 2019 14:59:38 GMT+0100 (CET)] error TypeError: First argument must be a positive number or an array
```

**Comment by andcastillo** [comment]
You get that error because you are trying to use the predict for the output object of the PCA. You must predict on your dataset instead. In this case _hashes_. Example: 
         `var reduced = components.predict(hashes, {nComponents: 2});` 
On the other hand I dont understand why you want to use PCA in a dataset with only one feature, or in a single entry with M features. That just don't have any sense.

**Comment by andcastillo** [comment]
@loretoparisi  Nice. N x M is correct. It was my mistake then.

**Comment by loretoparisi** [comment]
@andcastillo perfect! Closing then, thank you so much!
