### ISSUE TITLE
Add info in readme that dataset has to be ml-matrix

### ISSUE THREAD

**Issue by vorg** [mljs/pca#2]

**Comment by targos** [comment]
This is wrong. The dataset should be converted internally if it's not a ml-matrix object.
@JeffersonH44 you should be able to use Matrix.checkMatrix for this purpose.

**Comment by JeffersonH44** [comment]
But I'm seeing the code now and there is no need of the ml-matrix because the algorithm check if the dataset is instance of matrix I just forget it, I will change the doc.
