### ISSUE TITLE
How to use `getExplainedVariance` results?

### ISSUE THREAD

**Issue by N8python** [mljs/pca#24]
I ran `getExplainedVariance` on my dataset:
```js
const pca = new PCA(students);
console.log(pca.getExplainedVariance());
```
It worked fine, and I got a list of variances back - however, how do I tell which variance corresponds to which feature?

**Comment by jwist** [comment]
The explained variance is associated to the PC, not to the features directly. The first number correspond the the extend of variance explained by the first principal component, and so on.

**Comment by N8python** [comment]
Oh ok - how are the principal components correlated to the features (sorry, statistics noob here)

**Comment by N8python** [comment]
Never mind - I understand now. PCA is about reducing the dimensions of data, not about identifying redundant features.
