### ISSUE TITLE
Question - Plotting Ability

### ISSUE THREAD

**Issue by shadowstriker15** [mljs/pca#30]
Hello, first of all I want to give my thanks for the existence of this library. I don't have a lot of experience with multivariate analysis so forgive me if this is a dumb question but I was wondering if it's possible to plot the data generated from the analysis? For example, if you take a look at this [Python Plotly graph](https://plotly.com/python/pca-visualization/#2d-pca-scatter-plot), they are plotting using the data generated from sklearn. Is this something that is achievable with the data generated from this library? Thank you.

**Comment by maasencioh** [comment]
Hello, this is can be archived by adding the number of components, like in your example, so it will be something like this
```js
const pca = new PCA(dataset);
console.log(pca.predict(dataset, { nComponents: 2 }));
```
In this case, the response will be a `n x 2` matrix.

**Comment by shadowstriker15** [comment]
@maasencioh Great, exactly what I was looking for. I was previously playing around with the predict function but my resulting matrix's width was larger than two. Thank you greatly!

**Comment by maasencioh** [comment]
Thank you as well, this issue is the result of a lack of documentation, we'll iterate over it
