### ISSUE TITLE
Test doesn't run in Node.js 4.1

### ISSUE THREAD

**Issue by vorg** [mljs/pca#4]
I'm getting error while trying to call `new PCA(Matrix(dataset))`

```TypeError: Class constructors cannot be invoked without 'new'```

It should be `new PCA(new Matrix(dataset))`

What engine (node, iojs, babel) is this package targetting?

**Comment by JeffersonH44** [comment]
Ok, I fixed the test, I used other version of node but is better to have the 'new' in the test, it's more consistent.
