### ISSUE TITLE
Getting different results that numeric.js

### ISSUE THREAD

**Issue by vorg** [mljs/pca#5]
Trying to visualize eigenvectors of a point set:

<img width="512" alt="screen shot 2015-09-21 at 11 26 24" src="https://cloud.githubusercontent.com/assets/171001/9989820/d92db6c0-6053-11e5-8202-88ef776578d7.png">

I compared the results with numeric.js using this code:
http://davywybiral.blogspot.co.uk/2012/11/numeric-javascript.html

<img width="512" alt="screen shot 2015-09-21 at 11 26 10" src="https://cloud.githubusercontent.com/assets/171001/9989832/ea5741be-6053-11e5-8b35-4bd6b2cecf41.png">

**Comment by JeffersonH44** [comment]
Are you normalizing before apply PCA? because this method apply the normalization.

**Comment by vorg** [comment]
I see, so the eigenvector are for this new normalized dataset. So anything that's diagonal will get eigenvectors at 45deg. Hmm. What's the use of it then?

**Comment by JeffersonH44** [comment]
I don't understand your question. What's the problem with that?

**Comment by andcastillo** [comment]
@JeffersonH44, if you normalize the data, you have to correct a posteriory your components to be consistent with the initial scaling.

**Comment by vorg** [comment]
@JeffersonH44 Because normalization happens inside your library I don't know how to denormalize the eigenvectors back in order to match them with my original dataset.

**Comment by JeffersonH44** [comment]
Ahhh sorry, maybe I can put some methods but each instance of the pca has their own means and std attribute that you can use to denormalize.

**Comment by andcastillo** [comment]
But it is not trivial. You have to apply a rotation procedure to "re-scale" the components. The only preprocessing you can apply on the data inside PCA without changing the PC direction is to center.  The final user should re-introduce the means to obtain its original data.

**Comment by lpatiny** [comment]
Standardize should be optional, by default only center the data

**Comment by targos** [comment]
@vorg can you try with v0.1.0 ?
Standardization is now an option (off by default).
