### ISSUE TITLE
Documentation breaks TravisCI

### ISSUE THREAD

**Issue by maasencioh** [mljs/pca#7]
When the package is installed it push to docs, so it throws an error in TravisCI `fatal: empty ident name (for <travis@testing-worker-linux-docker-d81d9b9d-3397-linux-15.prod.travis-ci.org>) not allowed`

**Comment by targos** [comment]
fixed by https://github.com/mljs/pca/commit/ee51991f13bd99579b336a7fbf0797c5af2595dc

Documentation can now be generated and published with `cheminfo-tools`
