### ISSUE TITLE
Mixed ES6 and CJS causes issues in some enviroments

### ISSUE THREAD

**Issue by Hypercubed** [mljs/pca#8]
Thank you for ml-pca, we are using it in a browser project and so far looks great.  One issue we are having, however, is that the JS files in ml-pca and ml-matrix use ES6 features within a CJS file.  When using JSPM/SystemJS in the browser this means that the files are detected as CJS and not transpiled.

Here is a relevant SystemJS issue: https://github.com/systemjs/systemjs/issues/811

One your end I can see three approaches:

1) Use babel to transpile on publish.
2) Use ESM import/export syntax (this may force you to do #1 also).
3) Ignore it and wait for it to be fixed by JSPM/SystemJS (maybe next version).

**Comment by Hypercubed** [comment]
I giesd #1 is out.  It appears it is not possible to extent native classes using Babel.

**Comment by Hypercubed** [comment]
I"ve looked in detail at this issue.  There are several thins at play:

1) Because the modules are CJS JSPM will not mark them for transpiling.
2) Because they are not transpile ES6 features are left untouched in the bundle.  This prevents minification because UglifyJS does not support ES6.
3) Forcing transpiling does not work because ml-matrix uses ES6 class syntax to extend `Array`.  This is not something possible to support using a transpiler.

All this to say when using mljs tools in the browser minification (a common build step for browsers) is not possible.  I don't see a solution at the moment other than "don't minify".  You might want to add this as a note somewhere.

Feel free to close this issue.

**Comment by maasencioh** [comment]
Hello @Hypercubed, thanks for all the research and for use our packages, we'll add this request and as soon as we have any solution we'll notify this to you. Thanks again!

**Comment by targos** [comment]
Thanks for the detailed description of your problem.
It indeed impossible to transpile `ml-matrix` because of it's use of `extends Array`. This limitation expands to all the projects that have it as a dependency (almost all `mljs` projects now...). I will add a note in the README of `ml` and `ml-matrix` about that.
Unfortunately, I haven't found a way to minify without transpiling.

UglifyJS is actively working on a version that can handle ES6 [here]](https://github.com/mishoo/UglifyJS2/tree/harmony). I will look into it and see what can be done with it.

**Comment by targos** [comment]
@Hypercubed there were a few bug with the harmony branch of UglifyJS preventing the minification of `ml-matrix`. I believe they are now fixed.
If you can control what version of UglifyJS is used in your build phase, you can `npm i github:mishoo/UglifyJS2#harmony --save-dev` to use this branch.

**Comment by Hypercubed** [comment]
I believe this is working.  However, in my app `UglifyJS2#harmony` is now giving another error that I think is unrelated to ml-matrix.  I'll try to isolate and submit an issue to UglifyJS2.

**Comment by Hypercubed** [comment]
Indeed, the issue I am now having is unrelated to ml-matrix:  https://github.com/mishoo/UglifyJS2/issues/1228

**Comment by Hypercubed** [comment]
I managed to get ml-matrix@1.1.5 to transpile using [babel-plugin-transform-builtin-extend](https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend). I had no luck with 2.0.0.  I think the abstractMatrix abstraction is too much for the plugin.
