### ISSUE TITLE
Dimension of eigenvectors

### ISSUE THREAD

**Issue by hllwd** [mljs/pca#9]
Hi, by advance sorry if my question is stupid as I'm not en expert in statistics

I'm trying to implement a SOM algorithm and the best way to initiate neurons' vectors is by using PCA, 

I'm trying to understand the behavior of the generated eigenvectors but can't figure why I've got this on my unit tests: 

```javascript
  const dataSetSize = 10;
  const numDimensions1 = 3;
  const numDimensions2 = 11;

  // Matrix 1 generation
  const data = _.range(0, dataSetSize).map(vec => _.range(0, numDimensions1).map(val => Math.random());

 // Matrix 2 generation
  const data2 = _.range(0, dataSetSize).map(vec => _.range(0, numDimensions2).map(val => Math.random());

  const pca = new PCA(data, {
    center: true,
    scale: false,
  });

  const pca2 = new PCA(data2, {
    center: true,
    scale: false,
  });

  describe('eigenvectors:', () => {
    const eigenvectors = pca.getEigenvectors();
    const eigenvectors2 = pca2.getEigenvectors();
    it('should have as many eigenvectors than the num of dimensions on the dataset', () => {
      assert.strictEqual(eigenvectors.length, numDimensions1);
      assert.strictEqual(eigenvectors2.length, numDimensions2);
    });
    it('an eigenvector should have as many dimensions than a vector from the dataset', () => {
      assert.strictEqual(eigenvectors[0].length, numDimensions1);
      // FAIL:
      // assert.strictEqual(eigenvectors2[0].length, numDimensions2);
    });
  });
```

**Comment by hllwd** [comment]
To be more precise, the problem occurs as soon as the num of vectors in my dataset is superior to the num of their dimensions

**Comment by maasencioh** [comment]
Hello @hllwd, I'm not sure of you question, your asking why the last test fails or why the tests should pass it?

**Comment by hllwd** [comment]
Hi, thanks for answering! I'm asking why the last test fails

**Comment by maasencioh** [comment]
do you have an example? and why the dimensionality of your dataset it's bigger than the one that you give?
It's our pleasure to hear that someone is doing something else with our work 😄

**Comment by hllwd** [comment]
Here is an example: 

```javascript
import PCA from 'ml-pca';

  // 2 vectors of 3 dimensions
  const dataset = [
    [0,0,0],
    [1,1,1],
  ];
  const pca = new PCA(dataset);
  const eigenvectors = pca.getEigenvectors();
  // let's display PC1
  console.log(eigenvectors[0].length); // Expected: 3 but is equal to 2
```

If I had other data to my dataset, it works

```javascript
import PCA from 'ml-pca';
const dataset = [
    [0,0,0],
    [1,1,1],
    [2,2,2],
    [3,3,3],
    [4,4,4],
    [5,5,5],
  ];
  const pca = new PCA(dataset);
  const eigenvectors = pca.getEigenvectors();
  // let's display PC1
  console.log(eigenvectors[0].length); //  3 
```

Usually, my datasets have lots of data of few dimensions, but I'm working on a dataset of 155 stars with each 2800 measures, this how I've figured this

**Comment by maasencioh** [comment]
I'm not sure if that's actually wrong, because the length of the main diagonal in the [non-square case](http://math.stackexchange.com/questions/583938/do-non-square-matrices-have-eigenvalues) it's the expected eigenvectors length, but I'll discuss it with @JeffersonH44, that's actually the main maintainer of this repo and check your examples

**Comment by andcastillo** [comment]
I'm not sure if it related, but some days ago, I was trying to use the pca, and it looks like the EigenVectors are transposed. I found my principal components in the columns not in the rows.
To be checked by @JeffersonH44

**Comment by targos** [comment]
I think what you are looking for is the loadings matrix (available with `pca.getLoadings()'). It is effectively the transpose of the eigenvectors.

**Comment by hllwd** [comment]
@targos indeed! that's it... Sorry :D 
Thank you all for your reactivity!
